### ISSUE TITLE
Crash when using `smooth` post-processing

### ISSUE THREAD

**Issue by nkeim** [MikeSmithLabTeam/particletracker#10]
Attempting to run the `smooth` post processing on the example eye-tracking data crashes the GUI (reproduced multiple times).

This issue stems from my JOSS review (https://github.com/openjournals/joss-reviews/issues/3611) but I do not consider it critical for publication in that journal.

**Comment by mikesmithlab** [comment]
Do you have any more details or perhaps the output when it crashes as this is a bit difficult to troubleshoot?

**Comment by mikesmithlab** [comment]
Smooth appears to be a legacy name which uses the rolling_mean. The example tutorial references using mean and I think this is preferred. Far better to have users consciously aware of what they are doing to their data than a magic button that smooths. I am going to remove this in the CurrentDevelopment version.
