### ISSUE TITLE
Removing preprocessing methods in the wrong order causes crashes

### ISSUE THREAD

**Issue by JamesDownsLab** [MikeSmithLabTeam/particletracker#17]
If the list contains methods that rely on thresholding, removing threshold before these methods causes the program to crash

**Comment by mikesmithlab** [comment]
I've tried reproducing this: threshold + erosion; threshold + distance transform.
Neither seems to produce a crash on my windows machine.
Perhaps the combination is more specific could you try the combination you were doing and let me know?
