### ISSUE TITLE
Handle complex numbers in postprocessing

### ISSUE THREAD

**Issue by JamesDownsLab** [MikeSmithLabTeam/particletracker#20]
Would be useful to also calculate the phase and magnitude of any complex numbers that are calculated.

There is currently a very hacky if statement in the colourbar class that turns complex numbers into a phase for annotating but this isn't very nice.

**Comment by mikesmithlab** [comment]
resolved with new postprocessing method real_imag splits out real, imag, magnitude and phase into separate columns. Can be applied to any column resulting in new columns: columnname_re, columnname_imag, columnname_mag, columnname_ang
