### ISSUE TITLE
please create screencast videos

### ISSUE THREAD

**Issue by alexlib** [MikeSmithLabTeam/particletracker#3]
there are several steps which I could not reproduce following the documentation, but not sure if it's the lack of understanding of the procedures, or the order of actions or some combination of the installation and the misunderstanding of the steps. The screencasts of the examples would be useful. 
Especially I have difficulty to visualize links for the colloids case, but also many other steps are not clear. https://github.com/openjournals/joss-reviews/issues/3611

**Comment by mikesmithlab** [comment]
This is a really nice idea. I will try and produce a vid for each of the examples

**Comment by mikesmithlab** [comment]
I have now uploaded 7 screencast videos that cover the overview and 6 examples. Hopefully these make it much simpler to work through the different examples.

**Comment by alexlib** [comment]
> I have now uploaded 7 screencast videos that cover the overview and 6 examples. Hopefully these make it much simpler to work through the different examples.

thanks. where is it?

**Comment by alexlib** [comment]
Example 4 is without audio. https://www.youtube.com/watch?v=iyeOTgB47yk&list=PL56zLBbX0yZZw18yyMM9tD0fLrobmdbJG&index=5

**Comment by mikesmithlab** [comment]
> Example 4 is without audio. https://www.youtube.com/watch?v=iyeOTgB47yk&list=PL56zLBbX0yZZw18yyMM9tD0fLrobmdbJG&index=5

This has been resolved
