### ISSUE TITLE
Mac supported?

### ISSUE THREAD

**Issue by nkeim** [MikeSmithLabTeam/particletracker#4]
Since the documentation is aimed at non-experts, it would be best to state explicitly that the software works on the Mac (I use a Mac and did not encounter any critical problems with ParticleTracker). There might be a weaker, but still helpful, way to say this if the Mac is not officially supported. 

This issue stems from my JOSS review (https://github.com/openjournals/joss-reviews/issues/3611) but I do not consider it critical for publication in that journal.

**Comment by mikesmithlab** [comment]
This is helpful thanks. I guess we are just saying we haven't tested it on Mac! Good to know it still works! I have added a clear statement about the operating systems. Saying it should work on Windows, Linux and Mac but that it has only been thoroughly tested on Windows 10 and Ubuntu Linux.

**Comment by nkeim** [comment]
That's a great way to put it. Thanks!
