### ISSUE TITLE
How to use difference and rate postprocessing steps?

### ISSUE THREAD

**Issue by nkeim** [MikeSmithLabTeam/particletracker#7]
When looking at the example colloids results, I could not get the `difference` or `rate` postprocessing steps to work — I would just get a "difference error" or "rate error" message. For example, `column_name='x', output_name='vx', fps=50.0, span=3`. Is there a step I'm missing?

This issue stems from my JOSS review (https://github.com/openjournals/joss-reviews/issues/3611) but I do not consider it critical for publication in that journal.

**Comment by mikesmithlab** [comment]
Could you clarify if you have already run part_processed on the first 5 steps and then had selected the use_part_processed button. These features require data from multiple frames. They are only useable if you have a videoname.hdf5 file to work from?

**Comment by nkeim** [comment]
Yes, this is with tracking completed and use_part_processed turned on.

**Comment by mikesmithlab** [comment]
There was a small bug in this bit of code which I have fixed in the CurrentDevelopment Branch.
