### ISSUE TITLE
Glitch with `mask_rectangle`

### ISSUE THREAD

**Issue by nkeim** [MikeSmithLabTeam/particletracker#8]
When setting up a mask, I add a `mask_rectangle`, check the box to enable interactive drawing, and draw the region. If I then forgot to uncheck the box before adding another `mask_rectangle`, the first region I drew remains on the display and cannot be removed.

This issue stems from my JOSS review (https://github.com/openjournals/joss-reviews/issues/3611) but I do not consider it critical for publication in that journal.

**Comment by mikesmithlab** [comment]
Have resolved this in the CurrentDevelopment branch. Once I have checked and resolved other issues you raised will merge with Main.
